[package]
name = "ecdh"
version = "0.1.0"
authors = ["Tom Conroy <tjc25614@outlook.com>"]
edition = "2018"

[dependencies]
rand = "0.5"
num-bigint = { version = "0.2.2", features = ["rand"] }
num-traits = "0.2.4"
